apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-strings
data:
  JAVA_CONNECTION_STRING: jdbc:sqlserver://db:1433;database=TradeManagement;user=sa;password=Mypass123;encrypt=false;trustServerCertificate=false;loginTimeout=30;
  DOTNET_CONNECTION_STRING: Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=Mypass123;TrustServerCertificate=true
  GO_CONNECTION_STRING: sqlserver://sa:Mypass123@db:1433?database=TradeManagement&connection+encrypt=false&connection+TrustServerCertificate=false&connection+loginTimeout=30
